### ISSUE TITLE
valet's nginx is caching the servicer-worker.js, how to prevent this?

### ISSUE THREAD

**Issue by vesper8** [morrislaptop/WebpackDevServerValetDriver#8]
Wondering how to prevent this without manually editing the nginx generated file.

As a result of the service-worker.js being cached I have to go into the debugger's application tab and manually 'clear storage' after each deployment

this is how I handle not caching the service worker on production:

```
location = /service-worker.js {
    expires off;
    add_header Cache-Control no-cache;
    access_log off;
}
```

**Comment by morrislaptop** [comment]
I don't think this can be solved by the scope of this library...
